name: flutterfire
description: flutterfire mobile app.
version: 3.0.5+16

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  advance_pdf_viewer: ^1.2.0
  carousel_slider: ^2.3.1
  youtube_player_flutter: ^7.0.0+7
  firebase_dynamic_links: ^0.5.1
  sms_otp_auto_verify: ^1.2.2
  native_updater: ^0.0.3
  firebase_core: ^0.4.3+1
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.3
  firebase_messaging: ^6.0.9
  page_transition: ^1.1.6
  fluttertoast:
  file_picker: ^1.12.0
  firebase_storage: ^3.1.6
  flutter_native_admob: ^2.1.0+3
  url_launcher: ^5.4.11
  screenshot: ^0.1.1
  documents_picker: ^1.0.0
  path_provider: ^1.3.0
  flutter_share: ^1.0.2+1
  readmore: ^1.0.0

  google_sign_in: ^4.1.1
  google_sign_in_web: ^0.9.1


  flutter_facebook_login: ^3.0.0
  flutter_bloc: ^3.1.0
  equatable: ^1.0.1
  meta: ^1.1.8
  cached_network_image: ^2.0.0-rc
  timeago: ^2.0.27
  firebase_admob: ^0.9.3+4
  package_info: ^0.4.1

  cupertino_icons: ^0.1.3

  local_auth: ^0.6.1
  extended_image: ^0.6.8

dev_dependencies:
  flutter_launcher_icons: "^0.7.2+1"
  flutter_test:
    sdk: flutter
flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/icon_fb.jpg"
  image_path_ios: "assets/icon_fb.jpg"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"

flutter:
  uses-material-design: true
  assets:
    - assets/auth.png
    - assets/icons/log.png
    - assets/icons/video.png
    - assets/icons/stores.png


    - assets/icons/person.png
    - assets/icons/menu.png


    - assets/icons/featured.png
    - assets/icons/fb.png
    - assets/icons/google.png
    - assets/icons/loading.gif
    - assets/logo.png
    - assets/otp-icon.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
